In [3]:
import numpy as np
arr = np.array([12,4,56,7,29,10])
sorted_arr = np.sort(arr)
print("Original array:",arr)
print("Sorted array:",sorted_arr)

Original array: [12  4 56  7 29 10]
Sorted array: [ 4  7 10 12 29 56]


In [5]:
import numpy as np
array=np.array([[7,6,5],
                [8,3,9],
                [1,6,3]])
print("Original 2D array:")
print(array)

row_sorted_array = np.sort(array,axis=1)
print("\nRowwise sorted array:")
print(row_sorted_array)

column_sorted_array = np.sort(array,axis=0)
print("\nColumnwise sorted array:")
print(column_sorted_array)

Original 2D array:
[[7 6 5]
 [8 3 9]
 [1 6 3]]

Rowwise sorted array:
[[5 6 7]
 [3 8 9]
 [1 3 6]]

Columnwise sorted array:
[[1 3 3]
 [7 6 5]
 [8 6 9]]


In [11]:
import pandas as pd
l=[10,20,30]
S=pd.Series(l)
print(S)

0    10
1    20
2    30
dtype: int64


In [19]:
import pandas as pd
d={"StdID":[101,102,103],"Name":['Ram','Siya','Sam'],"Roll.no":[101,108,116]}
df=pd.DataFrame(d)
print(df)

   StdID  Name  Roll.no
0    101   Ram      101
1    102  Siya      108
2    103   Sam      116


In [23]:
import pandas as pd
d={"Name":['Alice','Bob','Charlie','David'],"Age":[24,27,22,32],"Department":['HR','Finance','IT','Marketing'],"Salary":[50000,60000,55000,65000]}
df=pd.DataFrame(d)
print(df)

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   27    Finance   60000
2  Charlie   22         IT   55000
3    David   32  Marketing   65000


In [29]:
import pandas as pd
d={"Name":['Alice','Bob','Charlie','David'],"Age":[24,27,22,32],"Department":['HR','Finance','IT','Marketing'],"Salary":[50000,60000,55000,65000]}
df=pd.DataFrame(d)
print(df)

print(df['Age'])
print(df['Name'])

print(df.loc[0])
print(df.loc[0:2])

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   27    Finance   60000
2  Charlie   22         IT   55000
3    David   32  Marketing   65000
0    24
1    27
2    22
3    32
Name: Age, dtype: int64
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
Name          Alice
Age              24
Department       HR
Salary        50000
Name: 0, dtype: object
      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   27    Finance   60000
2  Charlie   22         IT   55000
